version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mlflow_postgres
    restart: always
    environment:
      POSTGRES_DB: mlflow_db
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_pass
    volumes:
      - /home/ssclml/mlflow_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: mlflow_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - /mnt/drive1/mlflow:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow_server
    depends_on:
      - postgres
      - minio
    ports:
      - "3050:3050"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
